/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiLiberT;

import LiberT.Client;
import LiberT.GestionMethodesClient;
import LiberT.GestionMethodesVoiture;
import LiberT.Voiture;
import ServiceLiberT.ServiceClient;
import ServiceLiberT.ServiceVoiture;
import java.awt.Window;
import java.awt.event.MouseEvent;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.MatchResult;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;
import javax.swing.JComboBox;

/**
 *
 * @author Vitor
 */
public class GuiClientEtVoiture extends javax.swing.JFrame {

    Client client; Voiture voit;
    int idClientFK, idVoitureFK;
    List<Client> clients = new ArrayList<Client>();
    
    List<Voiture> voitures = new ArrayList<Voiture>();
    /**
     * Creates new form Client
     */
    public GuiClientEtVoiture() {
        this.setLocation(380, 240);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LiberT Simulateur - Identifier le Client et Voiture");

        jLabel1.setText("Selectionnez s'il vous plaît le client");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
        });

        jLabel2.setText("Selectionnez s'il vous plaît le voiture");

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox2MouseExited(evt);
            }
        });

        jButton1.setText("Suivant");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, 393, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        
        Client clientIndividuel = new Client();
        GestionMethodesClient gmc;
        boolean etat=false;
        ServiceClient sClient = new ServiceClient();
        try
        {
            
            gmc = sClient.ObtenirTousClient();
            if(gmc!= null)
            {
              //populate
              
                for (int i=0; i<gmc.ObtenbirConjointDeClients().size();)
                {
                    clientIndividuel = gmc.ObtenbirConjointDeClients().get(i);
                    clients.add(clientIndividuel);
                    
                    jComboBox1.addItem("Id: "+clientIndividuel.ObtenirIdClient()+" | Prénom: "+clientIndividuel.ObtenirPremierNomClient()+" | Nom: "+clientIndividuel.ObtenirNomClient());
                    i++;
                }
            }
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_jComboBox1MouseEntered

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:

        jComboBox2.removeAllItems();
        String clavierPrimaireER = "[0-9]{1,10}";
        
        Object obj = evt.getItem();
        String s = obj.toString();
       
        Pattern p = Pattern.compile(clavierPrimaireER);
        Matcher match = p.matcher(s);
        if(match.find())
        {
            int numeroId = Integer.parseInt(match.group());
            idClientFK=numeroId;
            for (int i=0; i<clients.size(); i++)
            {
                if(idClientFK == clients.get(i).ObtenirIdClient())
                {
                    client = clients.get(i);
                }
            }
            
            this.AppelRESTPourObtenirVoitureClient(numeroId);
            
        }
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseExited
        // TODO add your handling code here:
        
        
       
    }//GEN-LAST:event_jComboBox2MouseExited

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        
        String clavierPrimaireER = "[0-9]{1,10}";
        
        Object obj = evt.getItem();
        String s = obj.toString();
       
        Pattern p = Pattern.compile(clavierPrimaireER);
        Matcher match = p.matcher(s);
        if(match.find())
        {
            int numeroId = Integer.parseInt(match.group());
            idVoitureFK=numeroId;
            
            for (int i=0; i<voitures.size(); i++)
            {
                if(idVoitureFK==voitures.get(i).ObtenirClavierPrimaireVoiture())
                {
                    voit = voitures.get(i);
                }
            }

        }
        

    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        RegisterMouvement regMouv = new RegisterMouvement(client, voit);
        jComboBox2.removeAllItems();//??
        /*
        Window thisWind = new Window(this);
        Window nextWind = new Window(regMouv);
        //nextWind.setVisible(true);
        nextWind.setVisible(rootPaneCheckingEnabled);
        thisWind.setVisible(false);
        */
        this.hide();
        regMouv.setLocation(380, 240);
        regMouv.show();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiClientEtVoiture().setVisible(true);
            }
        });
    }
    
    public boolean AppelRESTPourObtenirVoitureClient(int clientId)
    {
        boolean etat=false;
        Voiture voiture = new Voiture();
        GestionMethodesVoiture gestionMethodesVoiture = new GestionMethodesVoiture();
        ServiceVoiture sVoiture = new ServiceVoiture();
        try
        {
            gestionMethodesVoiture= sVoiture.ObtenirTousLesVoitures(clientId);
            if(gestionMethodesVoiture != null)
            {
                for (int i=0; i<gestionMethodesVoiture.ObtenirTousVoitures().size(); )
                {
                    voiture = gestionMethodesVoiture.ObtenirTousVoitures().get(i);
                    voitures.add(voiture);
                    
                    jComboBox2.addItem("Id: "+voiture.ObtenirClavierPrimaireVoiture()+" | Marque: "+voiture.ObtenirMarque()+" | Model: "+voiture.Modelo()+" | Immatriculation: "+voiture.ImmatriculationVoiture());
                    i++;
                }
            }
            
            etat=true;
        }
        catch(Exception ex)
        {
            etat=false;
        }
        return etat;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
