/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiLiberT;

import LiberT.Client;
import LiberT.DoneesBancaires;
import LiberT.GestionMethodesDoneesBancaires;
import LiberT.GestionMethodesHotel;
import LiberT.GestionMethodesPark;
import LiberT.GestionMethodesPrixPeage;
import LiberT.GestionMethodesStationService;
import LiberT.Iteneraire;
import LiberT.PrixPeage;
import LiberT.Hotel;
import LiberT.MouvementPeage;
import LiberT.Park;
import LiberT.Payments;
import LiberT.StationService;
import LiberT.Voiture;
import ServiceLiberT.ServiceDoneesBancaires;
import ServiceLiberT.ServiceHotel;
import ServiceLiberT.ServiceMouvementPeage;
import ServiceLiberT.ServicePark;
import ServiceLiberT.ServicePrixPeage;
import ServiceLiberT.ServiceStationService;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Vitor
 */
public class RegisterMouvement extends javax.swing.JFrame {

    boolean resultatMouvPeage;
    PrixPeage iteneraireSelectionne;
    Client clientId;
    Voiture voitureId;
    Payments payment;
    DoneesBancaires dbanc;
    
    List<PrixPeage> listePrix = new ArrayList<PrixPeage>();
    List<Hotel> listeHotels = new ArrayList<Hotel>();
    List<Park> listeParks = new ArrayList<Park>();
    List<StationService> listeStations = new ArrayList<StationService>();
    int classPeage;
    
    
        
    /**
     * Creates new form RegisterMouvement
     */
    public RegisterMouvement() {

        initComponents();
        jTextField1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jComboBox2.setVisible(false);
        jLabel4.setVisible(false);
        jTextField2.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
    }
    
    public RegisterMouvement(Client client, Voiture voiture)
    {
       
        initComponents();
        this.clientId=client;
        this.voitureId = voiture;
        jTextField1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jComboBox2.setVisible(false);
        jLabel4.setVisible(false);
        jTextField2.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jComboBox3.setVisible(false);
       
        //JImageComponent ic = new JImageComponent("C:\\Users\\Vitor\\Documents\\NetBeansProjects\\WebService-LiberT\\img\\liberT-logo.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LiberT - Register Nouveau Mouvement (Donées)");

        jLabel1.setText("Espece Mouvement");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionnez...", "Mouvement Peage", "Mouvement Park Stationment", "Mouvement Station Service", "Mouvement Restaurant", "Mouvement Hotel", "Mouvement Ferry", " " }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel2.setText("Date du Mouvement");

        jTextField1.setToolTipText("Date du mouvement");

        jLabel3.setText("jLabel3");

        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jLabel4.setText("jLabel4");

        jTextField2.setEnabled(false);

        jLabel5.setText("Entrée en");

        jButton1.setText("Voir Details");

        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField3.setText("jTextField3");

        jLabel6.setText("Sorti en:");

        jTextField4.setText("jTextField4");

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        
        Object obj;
       
        obj=evt.getItem();
        String s = obj.toString();
        if(s=="Mouvement Peage")
        {
                //
           jTextField1.setVisible(true);
           jLabel2.setVisible(true);
           jLabel3.setText("Iteneraire");
           jLabel4.setText("Prix (€)");
           jLabel3.setVisible(true);
           jTextField2.setVisible(true);
           jTextField2.setEnabled(false);
           jLabel4.setVisible(true);
           jComboBox2.setVisible(true);
           jLabel5.setVisible(false);
           jLabel6.setVisible(false);
           jLabel7.setText("Payment Doneés");
           jLabel7.setVisible(true);
           jTextField3.setVisible(false);
           jTextField4.setVisible(false);
           jComboBox3.setVisible(true);
           ObtenirDoneesBancaires(clientId.ObtenirIdClient());
           if(jComboBox2.getItemCount()>0) // Nous avons d'elements
           {
               jComboBox2.removeAllItems();
               ObtenirDoneesIteneraire(voitureId.ObtenirClavierPrimaireVoiture());
   
           }
           else
           {
               ObtenirDoneesIteneraire(voitureId.ObtenirClavierPrimaireVoiture());
           }
           
           
           
        }
        else if(s=="Mouvement Park Stationment")
        {
           jLabel2.setVisible(true);
           jLabel3.setText("Park");
           jLabel4.setText("Prix (€)");
           jTextField1.setVisible(true);
           jLabel3.setVisible(true);
           jTextField2.setEnabled(true);
           jTextField2.setVisible(true);
           jLabel4.setVisible(true);
           jComboBox2.setVisible(true);
           jLabel5.setVisible(true);
           jLabel6.setVisible(true);
           jTextField3.setVisible(true);
           jTextField4.setVisible(true);
               jComboBox3.setVisible(true);
           if(jComboBox2.getItemCount()>0) // Nous avons d'elements
           {
               jComboBox2.removeAllItems();
               ObtenirDoneesParkStationment();  
           }
           else
           {
               ObtenirDoneesParkStationment();             
           }
           
           
           
        }
        else if(s=="Mouvement Station Service")
        {
           jLabel2.setVisible(true);
           jLabel3.setText("Park");
           jLabel4.setText("Prix (€)");
           jTextField1.setVisible(true);
           jLabel3.setVisible(true);
           jTextField2.setEnabled(true);
           jTextField2.setVisible(true);
           jLabel4.setVisible(true);
           jComboBox2.setVisible(true);
           jComboBox3.setVisible(true);
           jLabel7.setVisible(true);
           jTextField3.setVisible(false);
           jTextField4.setVisible(false);
           jLabel5.setVisible(false);
           jLabel6.setVisible(false);
           jComboBox3.setVisible(true);
           if(jComboBox2.getItemCount()>0)
           {
               jComboBox2.removeAllItems();
               ObtenirDoneesStationService();
           }
           else
           {
               ObtenirDoneesStationService();
           }
            
            
        }
        else if(s=="Mouvement Hotel")
        {
           jTextField1.setVisible(true);
           jLabel2.setVisible(true);
           jLabel3.setText("Hotel");
           jLabel4.setText("Prix (€)");
           jLabel3.setVisible(true);
           jTextField2.setEnabled(true);
           jTextField2.setVisible(true);
           jLabel4.setVisible(true);
           jComboBox2.setVisible(true);
           jLabel5.setVisible(false);
           jLabel6.setVisible(false);
           jTextField3.setVisible(false);
           jTextField4.setVisible(false);
           if(jComboBox2.getItemCount()>0) // Nous avons d'elements
           {
               jComboBox2.removeAllItems();
               ObtenirDoneesHotel();  
           }
           else
           {
               ObtenirDoneesHotel();
           }
           
   
        }
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private static void DisplayImage(JPanel jp, String url) {
   // JLabel jl=new JLabel();
    //jl.setIcon(new javax.swing.ImageIcon(getClass().getResource(url)));
    //jp.add(jl);
    
    }
    
    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        
    
           if(jComboBox1.getSelectedItem() == "Mouvement Peage")
            {
                
                String er = "ID\\s[0-9]{1,5}";
                Object obj = evt.getItem();
                String s = obj.toString();
       
                Pattern p = Pattern.compile(er);
                Matcher match = p.matcher(s);
                if(match.find())
                {
                    String matchResult = match.group().toString();
                    String nouveauER = "[0-9]{1,5}";
                    Pattern pII = Pattern.compile(nouveauER);
                    Matcher matchII = pII.matcher(matchResult);
                    if(matchII.find())
                    {
                        int numeroId = Integer.parseInt(matchII.group());
                        ObtenirIteneraireSelectionee(numeroId);
                        String prix = String.valueOf(iteneraireSelectionne.ObtenirPrixpeage());
                        jTextField2.setText(prix);
                        //        
                    }
                }
            }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        ServiceMouvementPeage servMouvPeage = new ServiceMouvementPeage();
        
        String dateduMouvement = jTextField1.getText();
       
        try
        {
           
            
            Date dt;
            //DateFormat df = DateFormat.getDateInstance(DateFormat.SHORT, Locale.FRANCE);
            
            //dt = //df.parse(dateduMouvement);
                    
            
            if(jComboBox1.getSelectedItem() == "Mouvement Peage")
            {
                
                //Nouveau mouvement de Peage
                MouvementPeage mouv = new MouvementPeage();
                mouv.DefinirDateDuMouvement(dateduMouvement);
                mouv.DefinirPrixPeage(iteneraireSelectionne);
                
                //Ajouter dans BD nouveau mouvement
                resultatMouvPeage = servMouvPeage.AdjouterEtRegisterMouvementDePeage(mouv);
                
                if(resultatMouvPeage==true)
                {
                    //Ajouter nouveau mouvement dans la table mouvements
                    //RegisterMouvementDePeage
                }
                
                
            }
            
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public PrixPeage ObtenirIteneraireSelectionee(int id)
    {
         for (int i=0; i<listePrix.size(); i++)
            {
                if(listePrix.get(i).ObtenirPrixPeageId() == id)
                    iteneraireSelectionne = listePrix.get(i);
            }
         return iteneraireSelectionne;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterMouvement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterMouvement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterMouvement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterMouvement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new RegisterMouvement().setVisible(true);
                
            }
        });
    }
    
    
    
    public boolean ObtenirDoneesStationService()
    {
        boolean etat=false;
        GestionMethodesStationService gestStations;
        ServiceStationService servStationService = new ServiceStationService();
        StationService station = new StationService();
      
        
        try
        {
           
            gestStations = servStationService.ReturnezTousStationsService();
            for(int i=0; i<gestStations.ObtenirListeStationsService().size();)
            {
                station = gestStations.ObtenirListeStationsService().get(i);
                listeStations.add(station);
                
                jComboBox2.addItem("ID "+station.ObtenirLeClavierPrimaire()+" | Marque: "+station.ObtenirNomStationService()+" | Adresse: "+station.ObtenirLAdresseStationService().ObtenirLieuDAdresse()+" | Ville: "+station.ObtenirLAdresseStationService().ObtenirVille());
                i++;
                
            }
            etat=true;
        }
        catch(Exception ex)
        {
            String s = ex.getMessage();
        }
        return etat;
    }
    
    
    public boolean ObtenirDoneesBancaires(int clientId)
    {
        boolean etat=false;
        GestionMethodesDoneesBancaires gmdb = new GestionMethodesDoneesBancaires();
        ServiceDoneesBancaires servDoneesBancaires = new ServiceDoneesBancaires();
        DoneesBancaires dbanc = new DoneesBancaires();
        
        
        try
        {
            gmdb = servDoneesBancaires.ObtenirDoneesbancaires(clientId);
            jComboBox3.addItem("ID "+gmdb.ObtenirDoneesBancaires().ObtenirClavierPrimaire()+" | Nom Banque: "+gmdb.ObtenirDoneesBancaires().ObtenirNomBanque()+" | NIB: "+gmdb.ObtenirDoneesBancaires().NombreDeNIB());
            etat=true;
            
            
        }
        catch(Exception ex)
        {
            
        }
        return etat;
    }
    
    public boolean ObtenirDoneesHotel()
    {
        boolean etat=false;
        GestionMethodesHotel gmh = new GestionMethodesHotel();
        ServiceHotel serviceDHotel = new ServiceHotel();
        Hotel hotelIndividuel = new Hotel();
        
        
        

        try
        {
            gmh = serviceDHotel.ObtenirTousLesHotels();
            for (int i=0; i<gmh.ObtenirConjointHotel().size();)
            {
                hotelIndividuel =gmh.ObtenirConjointHotel().get(i);    
                listeHotels.add(hotelIndividuel);
                jComboBox2.addItem("ID "+hotelIndividuel.ObtenirClavierPrimaire()+" | Nom: "+hotelIndividuel.ObtenirNomHotel()+" | Ville: "+hotelIndividuel.ObtenirLAdresse().ObtenirVille());
                i++;
            }
            
            etat=true;
            
            
        }
        catch(Exception ex)
        {
            
        } 
        return etat;
    }
    
    public boolean ObtenirDoneesParkStationment()
    {
        boolean etat=false;
        GestionMethodesPark gmp = new GestionMethodesPark();
        ServicePark sPark = new ServicePark();
        Park park = new Park();
        
        try
        {
            gmp = sPark.ObtenirTousLesParks();
            for (int i=0; i<gmp.ObtenirUnConjointParkStationment().size();)
            {
                park = gmp.ObtenirUnConjointParkStationment().get(i);
                listeParks.add(park);
                
                jComboBox2.addItem("ID "+park.ObtenirIDPark()+" | Nom: "+park.ObtenirNomPark()+" | Ville: "+park.ObtenirAdresse().ObtenirVille());
                i++;
                
                
            }
            etat=true;
        }
        catch(Exception ex)
        {
            
        }
        return etat;
    }
    public boolean ObtenirDoneesIteneraire(int voitureId)
    {
        
        String url, username, password, driver;
        Connection con; Statement st; ResultSet rs; 
        ServicePrixPeage sPrixPeage = new ServicePrixPeage();
        boolean etat=false;
        PrixPeage prix = new PrixPeage();
        //Iteneraire iteneraire = new Iteneraire();
  
        GestionMethodesPrixPeage gmpp;
        driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
        url = "jdbc:sqlserver://DESKTOP-VUQIPI7;databaseName=liberT";
        username = "sa";
        password = "zauwitch";
        
        
           try
           {
               Class.forName(driver);
               con = DriverManager.getConnection(url, username, password);
               st = con.createStatement();
               con.commit();
               
               String query = "Select * from dbo.Voiture WHERE dbo.Voiture.voitureId="+voitureId+"";
               rs = st.executeQuery(query);
               while(rs.next())
               {
                   classPeage = rs.getInt("classePeage");
               }
               
               gmpp = sPrixPeage.ObtenirTousPrixPeages(classPeage);
               
               for (int i=0; i<gmpp.ObtenirListePrixPeages().size();)
               {
                   prix = gmpp.ObtenirListePrixPeages().get(i);
                   listePrix.add(prix);
                   
                   jComboBox2.addItem("ID "+prix.ObtenirPrixPeageId()+" | AE: "+prix.ObtenirIdIteneraire().ObtenirAutoRoute()+" | Parti: "+prix.ObtenirIdIteneraire().ObtenirLieuParti()+" | Arrive: "+prix.ObtenirIdIteneraire().ObtenirLieuDArrive()+" | Prix: "+prix.ObtenirPrixpeage());
                   i++;
               }
               etat=true;
           }
           catch(Exception ex)
           {
               etat=false;
           }
           return etat;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
